version: '3'
services:
  vpn:
    image: ./
    volumes:
      - ./logs:/var/log
      - /lib/modules:/lib/modules
    ports:
      - 500:500/udp
      - 4500:4500/udp
    privileged: true
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    environment:
      - HOST_IP=${HOST_IP}
      - VPNUSER=${VPNUSER}
      - VPNPASS=${VPNPASS}
