version: '2.1'
services:
  vpn:
    build: ./
    image: vpn:experimental-1
    volumes:
      - ./scripts/vpn:/usr/bin/vpn
      - ./init.sh:/init.sh
      - ./logs:/var/log
      - ./keys:/data/key_files
      - /lib/modules:/lib/modules
    ports:
      - 500:500/udp
      - 4500:4500/udp
      - 40000:40000/tcp
      - 40001:40001/tcp
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1
      - 1.0.0.1
    env_file:
      - ./.env
